all: misat misat2 OGsat misat3 misat4

misat:	SAT-alumnes-h1.cpp
	g++ -O3 -Wall SAT-alumnes-h1.cpp -o misat

misat2: SAT-alumnes-H2.cpp
	g++ -O3 -Wall SAT-alumnes-H2.cpp -o misat2

misat3: SAT-alumnes-H3.cpp
	g++ -O3 -Wall SAT-alumnes-H3.cpp -o misat3

misat4: SAT-alumnes-H4.cpp
	g++ -O3 -Wall SAT-alumnes-H4.cpp -o misat4

OGsat: SAT-alumnesOG.cpp
	g++ -O3 -Wall SAT-alumnesOG.cpp -o OGsat


clean:
	rm -f misat OGsat